apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: apache
  namespace: dev
spec:
  interval: 5m
  chart:
    spec:
      chart: apache
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: apache
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: ghcr.io/mbaykara/sample-app
      tag: v0.1.3
    service:
      port: 8090
    env_map:
    - name: REGION
      value: "WEST CAPE"
