apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apache
  namespace: dev
spec:
  interval: 5m
  path: "./apps"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
