apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-creds
  namespace: default
spec:
  encryptedData:
    DB_PASSWORD: AgBCfPmsqlCFcEv1JLuyHQf9eMxpU67DM9ZFaUiaOSrDhyjTBrhFdEVj+L+ZCtnIL9KphEYw9Vd6QCutD44dyRAJxKaQ+aRAW1cmpAGgzLmDdVYrkKvxEjxwxbFiIgt15lejKiVMco/mPKy5suCcBdzgxW7izpOcucdxNRERYPC8q2f7fcu3ypwFSjEf3W6WIDGcCbVRRqYCv4Qcb2Cy7pvjMJ8uJn/eh3ZBjBIA9sHtYTMwd3scWJ/DL409vTPNOZyJ08TZ6FUbYvVJl9m+XOF8mto81b83Uu/33QiLcXrhwVwxX2h1zpt43mSxqNeFHSWogG21NEJCTfoEf0OoVJFc31rC3Vdf7N64IppHwDed4sEQE8AqmcsjoGYgywwzjMUNY1ZCTPIGkgRUsPitd8fUANrxuDrbLzPbz0JcilK18tszcZXAEWRHsQelz+xNUyr7cVtuyGAd4VGZxd5iEgm1B+IABol3ego7xLR5P/huEeFC95V535tIYWI89NFg19ugcEN/lX1SWhbf4uKkmB0v8scn4vu6WdRlRaH7pz7UR4p1qJ1l+7xmndxVvfCYuTmkknIp9Yx63yw5MVfUNGUO2taC8ECfAbQS41ce24S4V52aXvGiHnVYham9tHXcoOBeTeKixLKSq/MHIweyONRDpUJhYhBKDNvv51rcFAjrSPKcONx/R0iBjdbd42V7wwn8M1IUQ0lF9Uo=
    DB_USERNAME: AgAUs4so/UD2Efyp9XJmZZrtRsLFhLlQ94Q2x/vGCzPqJqyYiy/dWIr4tiNHtv9VIrCXVpFFiXq4UghtdY806iUDeuBQjgMrWiYhaLzganXChQEVtGA2+fm6ESZqKNTYuFkgL4nK+rY4YG4wvqYYkj/iKq9F8inoQda3it40+gCRQ/jMNsoEaEoLIobNLxrB7VIUUEBOsCfE0eUZxLijkXMgIHXBwQaq28JDs1fNDEBDDRLASHbdXxeP/FUDhxj+20VLDFTClxIxRDJ0s4q8YrrCz8zHOU54lVTTtoRUTLYKINDYLYQRg9Tdh+EzKMos5I8Xu+US+eCotY7RX6cZdeHIvsmQKt6kDmM+FnJ3ZatMxv1gKSbelrYqkZ6oYeAspD+ma/0rP+IqSvnc7GQ/3waU2BETjItH0rWl+UAMW7mS7ikJn5l7RJKb03xcecdTIFhRrBC438j9MXcqmSzFqhRjGck/OhXyPNP2sGI3yfL/OxFfaDioFOsnCPqLRMeCNHexTQptRoBXSxZcU4KNyCmKgctr2V82jpDhlXhfOsB8WBLB7fgL6z5wwhospMZhDvWfbkCniAEtRmPVzHvoburRWEnPMVOcyW/y+PIJB5MUOTv19T8WnxdWOHUPXIPz3aMjbJmCv9z4wqlM+UKKimwHnLMPVzWmTcG9Dbfn2cO1Lqjvp3PlcEwNvZLj4AedywnUVcLQlhqaIA==
  template:
    metadata:
      creationTimestamp: null
      name: db-creds
      namespace: default
---
